version: '3.7'

services:
  dev:
    # privileged: true
    image: yoctodev:0.1.0
    user: builder
    build:
      context: ./images/
      args:
        - no_proxy
        - http_proxy
        - https_proxy
      network: host
      target: dev
    volumes:
      - ~/.ssh/:/home/builder/.ssh/
      - .:/workspaces/yoctorasp/:cached
      - type: volume
        source: yoctoartifacts
        target: /workspaces/yoctorasp/yocto
    working_dir: /workspaces/yoctorasp/

  shellcheck:
    image: koalaman/shellcheck:v0.7.2
    volumes:
      - .:/workspaces/yoctorasp/
    working_dir: /workspaces/yoctorasp/

  container-structure-test:
    image: gcr.io/gcp-runtimes/container-structure-test:latest
    volumes:
      - .:/workspaces/yocto-project/
      - /var/run/docker.sock:/var/runt/docker.sock
    working_dir: /workspaces/yoctorasp/

  docs:
    build:
      context: ./images/
      target: DOCS
      dockerfile: docs.Dockerfile
    working_dir: /docs/
    volumes:
      - ./docs/:/docs/
volumes:
  yoctoartifacts:
    name: "yoctoartifacts"